version: '3.5'
services:

    # The Application
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - php-shropshire
        environment:
            - "APP_NAME=app"

    # NGINX
    web:
        build:
            context: ./
            dockerfile: docker/web/Dockerfile
        working_dir: /var/www
        networks:
            - php-shropshire
        depends_on:
            - app
        volumes:
            - ./public:/var/www/public
        ports:
            - 8000:80

    zookeeper:
        image: confluentinc/cp-zookeeper:5.0.0
        restart: always
        networks:
            - php-shropshire
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
        ports:
            - "2181:2181"

    kafka:
        image: confluentinc/cp-enterprise-kafka:5.0.0
        hostname: kafka
        networks:
            - php-shropshire
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
    php-shropshire:
        name: php-shropshire