<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>CatFacts</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            .container {
                text-align: center;
                width: 450px;
                display: inline-block
            }

            input[type=tel] {
                padding: 12px 20px;
                width: 90%;
            }

            input[type=submit] {
                padding: 12px 20px;
                width: 30%;
                float: right;
                margin-top: 10px;
            }
        </style>

        <script
                src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

        <script>
            $(document).ready(function() {
                $('.form').submit(function(event) {
                    event.preventDefault();

                    $.ajax({
                        type: 'POST',
                        url: '/subscribe/' + $('input[type=tel]').val(),
                        data: {},
                        timeout: 1000,
                        error: function (jqXHR, textStatus, errorThrown) {
                            $.alert({
                                title: 'Failure!',
                                content: 'There has been an error subscribing to cat facts! :(',
                            });
                        },
                        success: function (data, textStatus) {
                            if (data['success']) {
                                $.alert({
                                    title: 'Success!',
                                    content: 'You are now subscribed to cat facts!',
                                });
                            } else {
                                $.alert({
                                    title: 'Failure!',
                                    content: 'There has been an error subscribing to cat facts! :(',
                                });
                            }

                        }
                    });
                });
            });
        </script>
    </head>
    <body>
        <h1>Cat Facts</h1>
        <div class="container">
            <form class="form">
                <input type="tel" name="mobile" placeholder="Enter your mobile number"/>
                <input type="submit" value="Subscribe"/>
            </form>
        </div>
    </body>
</html>
